/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppDataSourcesRouteImport } from './routes/app.data-sources'
import { Route as AppExperimentsRouteImport } from './routes/app.experiments'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppReauditRouteImport } from './routes/app.reaudit'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppExperimentsIdRouteImport } from './routes/app.experiments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsRoute = AppExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppReauditRoute = AppReauditRouteImport.update({
  id: '/reaudit',
  path: '/reaudit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsIdRoute = AppExperimentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppExperimentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/experiments': typeof AppExperimentsRouteWithChildren
  '/app/memory': typeof AppMemoryRoute
  '/app/reaudit': typeof AppReauditRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/experiments/$id': typeof AppExperimentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/audit': typeof AppAuditRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/experiments': typeof AppExperimentsRouteWithChildren
  '/app/memory': typeof AppMemoryRoute
  '/app/reaudit': typeof AppReauditRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/experiments/$id': typeof AppExperimentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/audit': typeof AppAuditRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/experiments': typeof AppExperimentsRouteWithChildren
  '/app/memory': typeof AppMemoryRoute
  '/app/reaudit': typeof AppReauditRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/experiments/$id': typeof AppExperimentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/audit'
    | '/app/data-sources'
    | '/app/experiments'
    | '/app/memory'
    | '/app/reaudit'
    | '/app/settings'
    | '/app/'
    | '/app/experiments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/audit'
    | '/app/data-sources'
    | '/app/experiments'
    | '/app/memory'
    | '/app/reaudit'
    | '/app/settings'
    | '/app'
    | '/app/experiments/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/audit'
    | '/app/data-sources'
    | '/app/experiments'
    | '/app/memory'
    | '/app/reaudit'
    | '/app/settings'
    | '/app/'
    | '/app/experiments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-sources': {
      id: '/app/data-sources'
      path: '/data-sources'
      fullPath: '/app/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments': {
      id: '/app/experiments'
      path: '/experiments'
      fullPath: '/app/experiments'
      preLoaderRoute: typeof AppExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reaudit': {
      id: '/app/reaudit'
      path: '/reaudit'
      fullPath: '/app/reaudit'
      preLoaderRoute: typeof AppReauditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments/$id': {
      id: '/app/experiments/$id'
      path: '/$id'
      fullPath: '/app/experiments/$id'
      preLoaderRoute: typeof AppExperimentsIdRouteImport
      parentRoute: typeof AppExperimentsRoute
    }
  }
}

interface AppExperimentsRouteChildren {
  AppExperimentsIdRoute: typeof AppExperimentsIdRoute
}

const AppExperimentsRouteChildren: AppExperimentsRouteChildren = {
  AppExperimentsIdRoute: AppExperimentsIdRoute,
}

const AppExperimentsRouteWithChildren = AppExperimentsRoute._addFileChildren(
  AppExperimentsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppExperimentsRoute: typeof AppExperimentsRouteWithChildren
  AppMemoryRoute: typeof AppMemoryRoute
  AppReauditRoute: typeof AppReauditRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppExperimentsRoute: AppExperimentsRouteWithChildren,
  AppMemoryRoute: AppMemoryRoute,
  AppReauditRoute: AppReauditRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
